fixtures:
  repositories:
    stdlib:        "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    apache:        "git://github.com/puppetlabs/puppetlabs-apache.git"
    vcsrepo:       "git://github.com/puppetlabs/puppetlabs-vcsrepo.git"
    postgresql:    "git://github.com/puppetlabs/puppetlabs-postgresql.git"
    mongodb:       "git://github.com/puppetlabs/puppetlabs-mongodb.git"
    foreman:       "git://github.com/theforeman/puppet-foreman.git"
    concat:
      repo:        "git://github.com/puppetlabs/puppetlabs-concat.git"
      branch:        "1.2.x"
    concat_native: "git://github.com/theforeman/puppet-concat"
    certs:         "git://github.com/katello/puppet-certs.git"
    katello:       "git://github.com/katello/puppet-katello.git"
    common:        "git://github.com/katello/puppet-common.git"
    candlepin:     "git://github.com/katello/puppet-candlepin.git"
    pulp:          "git://github.com/katello/puppet-pulp.git"
    crane:         "git://github.com/katello/puppet-crane.git"
    qpid:          "git://github.com/katello/puppet-qpid.git"
    elasticsearch: "git://github.com/katello/puppet-elasticsearch.git"
  symlinks:
    katello_devel: "#{source_dir}"
