forge 'https://forgeapi.puppetlabs.com'

mod 'katello-candlepin',        '1.0.1'
mod 'katello-capsule',          '2.0.0'
mod 'katello-certs',            '0.4.0'
mod 'katello-common',           '0.1.3'
mod 'katello-crane',            '0.1.1'
mod 'katello-gutterball',       '0.3.0'
mod 'katello-katello',          '3.0.0'
mod 'katello-pulp',             '3.1.0'
mod 'katello-qpid',             '1.2.2'
mod 'katello-service_wait',     '0.1.2'
