#!/bin/bash
#
# Simple script which updates all git submodules
#
# Frustrated form `git submodule` and following the hints from
#
#   http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/
#
# This script keeps the list of external modules we have and updates them.
#
# To add a new module, add it to this file using `update_module`, `update_foreman_module` or `update_katello_module`.
#
# To update the modules run:
#
# ./update_submodules $SOURCE [$NAME]
#
# where $SOURCE might be "thirdparty", "foreman" or "katello"
# when $NAME specified, only specific module will be updated.

set -exo pipefail

SOURCE=$1
NAME=$2

FOREMAN_INSTALLER_DIR=foreman-installer
FOREMAN_INSTALLER_URL=git@github.com:theforeman/foreman-installer.git
# we need to create a ref to be able to subtree from the submodule
REF=node-installer
FOREMAN_BRANCH=develop
if ! [ -e $FOREMAN_INSTALLER_DIR ]; then
  git clone $FOREMAN_INSTALLER_URL $FOREMAN_INSTALLER_DIR
fi
pushd $FOREMAN_INSTALLER_DIR > /dev/null;
   git checkout $FOREMAN_BRANCH
   git pull
   git submodule update --init
popd > /dev/null

update_submodule () {
    name=$1
    url=$2
    branch=${3:-master}
    path=modules/$name
    if [ -z "$NAME" -o "$NAME" = "$name" ]; then
        if [ -e $path ]; then
	    command="pull"
        else
	    command="add"
        fi
	echo $branch
        git subtree $command --prefix $path $url $branch --squash
    fi
}


update_foreman_submodule () {
    name=$1
    pushd $FOREMAN_INSTALLER_DIR/modules/$name > /dev/null
        if [ $(git rev-parse --abbrev-ref HEAD) != $REF ]; then
            if git branch | grep $REF; then
                git branch -D $REF
            fi
            git checkout -b $REF
        fi
    popd> /dev/null
    update_submodule $name $FOREMAN_INSTALLER_DIR/modules/$name $REF
}

update_katello_submodule () {
    name=$1
    update_submodule $name https://github.com/Katello/puppet-$name
}

if [ "$SOURCE" = 'thirdparty' ]; then
  update_submodule mongodb https://github.com/puppetlabs/puppetlabs-mongodb
elif [ "$SOURCE" = 'katello' ]; then
  update_katello_submodule apache
  update_katello_submodule certs
  update_katello_submodule elasticsearch
  update_katello_submodule kafo
  update_katello_submodule katello
  update_katello_submodule pulp
  update_katello_submodule qpid
  update_katello_submodule service_wait
elif [ "$SOURCE" = 'foreman' ]; then
  update_foreman_submodule create_resources
  update_foreman_submodule concat
  update_foreman_submodule concat_native
  update_foreman_submodule stdlib
  update_foreman_submodule dhcp
  update_foreman_submodule dns
  update_foreman_submodule tftp
  update_foreman_submodule xinetd
  update_foreman_submodule puppet
  update_foreman_submodule postgresql
  update_foreman_submodule git
  update_foreman_submodule passenger
  update_foreman_submodule foreman_proxy
  update_foreman_submodule foreman
else
  echo "Unkown puppet modules source: $SOURCE"
  exit 1
fi



