#!/bin/bash
#
# Simple script which updates all git submodules
#
# Frustrated form `git submodule` and following the hints from
#
#   http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/
#
# This script keeps the list of external modules we have and updates them.
# If argument specified, only this module is updated.
#
# To add a new module, add it to this file and run `update_sumodules your-new-module`

NAME=$1

update_submodule () {
    name=$1
    url=$2
    branch=${3:-master}
    path=modules/$name
    if [ -z "$NAME" -o "$NAME" = "$name" ]; then
        if [ -e $path ]; then
           command=pull
        else
           command=add
        fi
        git subtree $command --prefix $path $url $branch --squash
    fi
}


update_foreman_submodule () {
    FOREMAN_INSTALLER_DIR=foreman-installer
    FOREMAN_INSTALLER_URL=git@github.com:theforeman/foreman-installer.git
    # we need to create a ref to be able to subtree from the submodule
    REF=node-installer
    name=$1
    if ! [ -e $FOREMAN_INSTALLER_DIR ]; then
      git clone $FOREMAN_INSTALLER_URL $FOREMAN_INSTALLER_DIR
    fi
    pushd $FOREMAN_INSTALLER_DIR > /dev/null;
      git pull
      git submodule update --init
      pushd modules/$name > /dev/null
          if [ $(git rev-parse --abbrev-ref HEAD) != $REF ]; then
              if git branch | grep $REF; then
                  git branch -d $REF
              fi
              git checkout -b $REF
          fi
      popd> /dev/null
    popd > /dev/null;
    update_submodule $name $FOREMAN_INSTALLER_DIR/modules/$name $REF
}


update_submodule mongodb https://github.com/puppetlabs/puppetlabs-mongodb
update_submodule apache https://github.com/theforeman/puppet-apache
update_foreman_submodule create_resources
update_foreman_submodule concat_native
update_foreman_submodule stdlib
update_foreman_submodule dhcp
update_foreman_submodule dns
update_foreman_submodule tftp
update_foreman_submodule xinetd
update_foreman_submodule puppet
update_foreman_submodule foreman_proxy
update_foreman_submodule foreman
