name    'theforeman-passenger'
version '1.3.0-rc4'
source 'git://github.com/theforeman/puppet-passenger'
author 'theforeman'
license 'GPLv3+'
summary 'Phusion Passenger server configuration'
description 'Module for configuring Phusion Passenger'
project_page 'http://github.com/theforeman/foreman-installer'

dependency 'theforeman/apache', '>= 1.3.0-rc4'
