fixtures:
  repositories:
    apache:        "git://github.com/puppetlabs/puppetlabs-apache.git"
    stdlib:        "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat:
      repo: "git://github.com/puppetlabs/puppetlabs-concat.git"
      branch: "1.2.x"
    concat_native: "git://github.com/theforeman/puppet-concat_native.git"
    foreman_proxy: "git://github.com/theforeman/puppet-foreman_proxy.git"
    dhcp:          "git://github.com/theforeman/puppet-dhcp"
    dns:           "git://github.com/theforeman/puppet-dns"
    foreman:       "git://github.com/theforeman/puppet-foreman"
    puppet:        "git://github.com/theforeman/puppet-puppet"
    tftp:          "git://github.com/theforeman/puppet-tftp"
    xinetd:        "git://github.com/puppetlabs/puppetlabs-xinetd.git"
    common:        "git://github.com/katello/puppet-common.git"
    certs:         "git://github.com/katello/puppet-certs.git"
    qpid:          "git://github.com/katello/puppet-qpid.git"
    crane:         "git://github.com/katello/puppet-crane.git"
    pulp:          "git://github.com/katello/puppet-pulp.git"
    mongodb:       "git://github.com/puppetlabs/puppetlabs-mongodb.git"
  symlinks:
    capsule: "#{source_dir}"
