fixtures:
  repositories:
    stdlib:  "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    foreman: "git://github.com/theforeman/puppet-foreman.git"
    concat:
      repo:        "git://github.com/ripienaar/puppet-concat.git"
      ref:         "04356974f72b90a1d0f57346a00e95a717924e43"
    concat_native: "git://github.com/theforeman/puppet-concat.git"
    postgresql:    "git://github.com/puppetlabs/puppetlabs-postgresql.git"
