---
certs:
  generate: true
  deploy: true
  group: foreman
katello:
  package_names:
    - katello-sam
foreman:
  organizations_enabled: true
  locations_enabled: true
  initial_organization: Default Organization
  initial_location: Default Location
  custom_repo: true
  configure_epel_repo: false
  configure_scl_repo: false
  ssl: true
  server_ssl_cert: /etc/pki/katello/certs/katello-apache.crt
  server_ssl_key: /etc/pki/katello/private/katello-apache.key
  server_ssl_ca: /etc/pki/katello/certs/katello-default-ca.crt
  server_ssl_chain: /etc/pki/katello/certs/katello-default-ca.crt
  client_ssl_cert: /etc/foreman/client_cert.pem
  client_ssl_key: /etc/foreman/client_key.pem
  client_ssl_ca: /etc/foreman/proxy_ca.pem
  websockets_encrypt: true
  websockets_ssl_key: /etc/pki/katello/private/katello-apache.key
  websockets_ssl_cert: /etc/pki/katello/certs/katello-apache.crt
  smart_proxy: false

foreman::plugin::hooks: true
foreman::plugin::tasks: true
