---
  :log_dir: /var/log/capsule-installer
  :log_name: capsule-installer.log
  :log_level: DEBUG

  :no_prefix: true
  :answer_file: "./config/answers.capsule-installer.yaml"
  :installer_dir: "."
  :default_values_dir: "./config"
  :modules_dir: "./modules"
  :hook_dirs: ["./hooks"]
  :colors: true
  :order:
    - certs
    - capsule
    - foreman_proxy
  :mapping:
    :foreman_proxy::plugin::abrt:
      :manifest_name: plugin/abrt
      :params_name: plugin/abrt/params
      :dir_name: foreman_proxy
    :foreman_proxy::plugin::chef:
      :manifest_name: plugin/chef
      :params_name: plugin/chef/params
      :dir_name: foreman_proxy
    :foreman_proxy::plugin::dns::powerdns:
      :manifest_name: plugin/dns/powerdns
      :params_name: plugin/dns/powerdns/params
      :dir_name: foreman_proxy
    :foreman_proxy::plugin::dynflow:
      :manifest_name: plugin/dynflow
      :params_name: plugin/dynflow/params
      :dir_name: foreman_proxy
    :foreman_proxy::plugin::openscap:
      :manifest_name: plugin/openscap
      :params_name: plugin/openscap/params
      :dir_name: foreman_proxy
    :foreman_proxy::plugin::pulp:
      :manifest_name: plugin/pulp
      :params_name: plugin/pulp/params
      :dir_name: foreman_proxy
    :foreman_proxy::plugin::remote_execution::ssh:
      :manifest_name: plugin/remote_execution/ssh
      :params_name: plugin/remote_execution/ssh/params
      :dir_name: foreman_proxy
    :foreman_proxy::plugin::salt:
      :manifest_name: plugin/salt
      :params_name: plugin/salt/params
      :dir_name: foreman_proxy
