---
:name: Foreman Proxy
:description: Install a stand-alone Foreman Proxy.
:log_dir: /var/log/foreman-installer
:log_name: foreman-proxy-content.log
:log_level: DEBUG
:no_prefix: false
:answer_file: ./config/foreman-proxy-content-answers.yaml
:installer_dir: .
:default_values_dir: /tmp
:module_dirs:
- ./_build/modules
- ../katello-installer/modules
:parser_cache_path:
- /usr/share/foreman-installer/parser_cache/foreman.yaml
- /usr/share/katello-installer-base/parser_cache/katello.yaml
:hiera_config: /usr/share/foreman-installer/config/foreman-hiera.conf
:hook_dirs:
- ./hooks
:colors: true
:order:
- certs
- foreman_proxy
- foreman_proxy::plugin::pulp
- foreman_proxy_content
- puppet
# Unused, but remains present for older config migrations
:mapping: {}
