---
  :log_dir: /var/log/katello-devel-installer
  :log_name: katello-devel-installer.log
  :log_level: DEBUG
  :no_prefix: true
  :answer_file: "./config/answers.katello-devel-installer.yaml"
  :installer_dir: "."
  :modules_dir: "./modules"
  :default_values_dir: "./config"
  :colors: true
  :order:
    - certs
    - katello_devel
    - foreman_proxy
  :password: l7VtnWiPeKe412o2CVBM6yVbTkKGh6L_CKx4_zBkmUE

  :mapping:
    :katello_devel::plugin::gutterball:
      :dir_name: katello_devel
      :manifest_name: plugin/gutterball
    :katello_devel::plugin::foreman_gutterball:
      :dir_name: katello_devel
      :manifest_name: plugin/foreman_gutterball
    :foreman_proxy::plugin::pulp:
      :manifest_name: plugin/pulp
      :params_name: plugin/pulp/params
      :dir_name: foreman_proxy
