---
certs:
  generate: true
  deploy: true
  group: foreman
katello: true
foreman:
  organizations_enabled: true
  locations_enabled: true
  initial_organization: Default Organization
  initial_location: Default Location
  custom_repo: true
  configure_epel_repo: false
  configure_scl_repo: false
  ssl: true
  server_ssl_cert: /etc/pki/katello/certs/katello-apache.crt
  server_ssl_key: /etc/pki/katello/private/katello-apache.key
  server_ssl_ca: /etc/pki/katello/certs/katello-default-ca.crt
  server_ssl_chain: /etc/pki/katello/certs/katello-default-ca.crt
  server_ssl_crl: false
  websockets_encrypt: true
  websockets_ssl_key: /etc/pki/katello/private/katello-apache.key
  websockets_ssl_cert: /etc/pki/katello/certs/katello-apache.crt
foreman_proxy:
  custom_repo: true
  puppetca: true
  http: true
  http_port: '8000'
  ssl_port: '9090'
  register_in_foreman: true
  templates: false
  tftp: false
  ssl_ca: /etc/foreman-proxy/ssl_ca.pem
  ssl_cert: /etc/foreman-proxy/ssl_cert.pem
  ssl_key: /etc/foreman-proxy/ssl_key.pem
  foreman_ssl_ca: /etc/foreman-proxy/foreman_ssl_ca.pem
  foreman_ssl_cert: /etc/foreman-proxy/foreman_ssl_cert.pem
  foreman_ssl_key: /etc/foreman-proxy/foreman_ssl_key.pem
capsule:
  pulp_master: true
  puppet: true

katello::plugin::gutterball: true

foreman::cli: true
foreman::plugin::bootdisk: false
foreman::plugin::chef: false
foreman::plugin::cockpit: false
foreman::plugin::default_hostgroup: false
foreman::plugin::dhcp_browser: false
foreman::plugin::digitalocean: false
foreman::plugin::discovery: false
foreman::plugin::docker: false
foreman::plugin::memcache: false
foreman::plugin::openscap: false
foreman::plugin::ovirt_provision: false
foreman::plugin::tasks: true
foreman::plugin::hooks: false
foreman::plugin::puppetdb: false
foreman::plugin::remote_execution: false
foreman::plugin::salt: false
foreman::plugin::setup: false
foreman::plugin::templates: false
foreman::compute::ec2: false
foreman::compute::gce: false
foreman::compute::libvirt: false
foreman::compute::openstack: false
foreman::compute::ovirt: false
foreman::compute::rackspace: false
foreman::compute::vmware: false
foreman_proxy::plugin::abrt: false
foreman_proxy::plugin::chef: false
foreman_proxy::plugin::discovery: false
foreman_proxy::plugin::dns::powerdns: false
foreman_proxy::plugin::dynflow: false
foreman_proxy::plugin::openscap: false
foreman_proxy::plugin::pulp: false
foreman_proxy::plugin::remote_execution::ssh: false
foreman_proxy::plugin::salt: false
