---
certs:
  generate: true
  deploy: true
  group: foreman
katello: true
foreman:
  organizations_enabled: true
  locations_enabled: true
  initial_organization: Default Organization
  initial_location: Default Location
  custom_repo: true
  configure_epel_repo: false
  configure_scl_repo: false
  ssl: true
  server_ssl_cert: /etc/pki/katello/certs/katello-apache.crt
  server_ssl_key: /etc/pki/katello/private/katello-apache.key
  server_ssl_ca: /etc/pki/katello/certs/katello-default-ca.crt
  server_ssl_chain: /etc/pki/katello/certs/katello-default-ca.crt
  server_ssl_crl: false
  client_ssl_cert: /etc/pki/katello/certs/katello-apache.crt
  client_ssl_key: /etc/pki/katello/private/katello-apache.key
  client_ssl_ca: /etc/pki/katello/certs/katello-default-ca.crt
  websockets_encrypt: true
  websockets_ssl_key: /etc/pki/katello/private/katello-apache.key
  websockets_ssl_cert: /etc/pki/katello/certs/katello-apache.crt
capsule:
  register_in_foreman: true
  pulp_master: true
  puppet: true
  puppetca: true
  templates: false

foreman::plugin::bootdisk: false
foreman::plugin::discovery: false
foreman::plugin::hooks: false
foreman::plugin::tasks: true
foreman::plugin::chef: false
foreman::plugin::default_hostgroup: false
foreman::plugin::openscap: false
foreman::plugin::puppetdb: false
foreman::plugin::setup: false
foreman::plugin::templates: false
foreman::plugin::remote_execution: false

foreman_proxy::plugin::openscap: false
foreman_proxy::plugin::remote_execution::ssh: false

katello::plugin::gutterball: true

# Issue #4244 - Commenting these out due to the seg fault
# caused on Ruby 1.8.7, the Katello RPM ensures these
# are installed instead
#foreman::compute::ec2: true
#foreman::compute::gce: true
#foreman::compute::libvirt: true
#foreman::compute::openstack: false
#foreman::compute::ovirt: true
#foreman::compute::rackspace: false
#foreman::compute::vmware: true
