---
  :name: Katello devel
  :description:
  :product_name: Katello
  :log_dir: /var/log/foreman-installer
  :log_name: katello-devel.log
  :log_level: DEBUG
  :no_prefix: false
  :answer_file: "./config/katello-devel-answers.yaml"
  :installer_dir: "."
  :default_values_dir: "/tmp"
  :module_dirs: ["./_build/modules", "../katello-installer/modules"]
  :hiera_config: /usr/share/foreman-installer/config/foreman-hiera.conf
  :hook_dirs: ["../katello-installer/hooks"]

  :colors: true
  :order:
    - certs
    - katello_devel
    - foreman_proxy
  :password: l7VtnWiPeKe412o2CVBM6yVbTkKGh6L_CKx4_zBkmUE

  :mapping:
    :foreman_proxy::plugin::pulp:
      :manifest_name: plugin/pulp
      :params_name: plugin/pulp/params
      :dir_name: foreman_proxy
