---
  :log_dir: /var/log/katello-installer
  :log_name: katello-installer.log
  :log_level: DEBUG
  :no_prefix: false
  :answer_file: "./config/answers.katello-installer.yaml"
  :installer_dir: "."
  :modules_dir: "./modules"
  :hook_dirs: ["./hooks"]
  :default_values_dir: "./config"
  :colors: true
  :password: l7VtnWiPeKe412o2CVBM6yVbTkKGh6L_CKx4_zBkmUE
  :order:
    - certs
    - foreman
    - katello
    - capsule
    - foreman_proxy

  # The mapping hash provides Kafo with the information to find plugin classes
  :mapping:
    :katello::plugin::gutterball:
      :dir_name: katello
      :manifest_name: plugin/gutterball
    :foreman::plugin::bootdisk:
      :dir_name: foreman
      :manifest_name: plugin/bootdisk
    :foreman::plugin::puppetdb:
      :dir_name: foreman
      :manifest_name: plugin/puppetdb
      :params_name: plugin/puppetdb/params
    :foreman::plugin::hooks:
      :dir_name: foreman
      :manifest_name: plugin/hooks
    :foreman::plugin::discovery:
      :dir_name: foreman
      :manifest_name: plugin/discovery
      :params_name: plugin/discovery/params
    :foreman::plugin::chef:
      :dir_name: foreman
      :manifest_name: plugin/chef
    :foreman::plugin::tasks:
      :dir_name: foreman
      :manifest_name: plugin/tasks
      :params_name: plugin/tasks/params
    :foreman::plugin::templates:
      :dir_name: foreman
      :manifest_name: plugin/templates
    :foreman::plugin::remote_execution:
      :dir_name: foreman
      :manifest_name: plugin/remote_execution
      :params_name: plugin/remote_execution/params
    :foreman::plugin::setup:
      :dir_name: foreman
      :manifest_name: plugin/setup
    :foreman::plugin::default_hostgroup:
      :dir_name: foreman
      :manifest_name: plugin/default_hostgroup
    :foreman::compute::rackspace:
      :dir_name: foreman
      :manifest_name: compute/rackspace
    :foreman::compute::openstack:
      :dir_name: foreman
      :manifest_name: compute/openstack
    :foreman::compute::vmware:
      :dir_name: foreman
      :manifest_name: compute/vmware
    :foreman::compute::libvirt:
      :dir_name: foreman
      :manifest_name: compute/libvirt
    :foreman::compute::ec2:
      :dir_name: foreman
      :manifest_name: compute/ec2
    :foreman::compute::gce:
      :dir_name: foreman
      :manifest_name: compute/gce
    :foreman::compute::ovirt:
      :dir_name: foreman
      :manifest_name: compute/ovirt
    :foreman_proxy::plugin::abrt:
      :manifest_name: plugin/abrt
      :params_name: plugin/abrt/params
      :dir_name: foreman_proxy
    :foreman_proxy::plugin::chef:
      :manifest_name: plugin/chef
      :params_name: plugin/chef/params
      :dir_name: foreman_proxy
    :foreman_proxy::plugin::dns::powerdns:
      :manifest_name: plugin/dns/powerdns
      :params_name: plugin/dns/powerdns/params
      :dir_name: foreman_proxy
    :foreman_proxy::plugin::dynflow:
      :manifest_name: plugin/dynflow
      :params_name: plugin/dynflow/params
      :dir_name: foreman_proxy
    :foreman_proxy::plugin::openscap:
      :manifest_name: plugin/openscap
      :params_name: plugin/openscap/params
      :dir_name: foreman_proxy
    :foreman_proxy::plugin::pulp:
      :manifest_name: plugin/pulp
      :params_name: plugin/pulp/params
      :dir_name: foreman_proxy
    :foreman_proxy::plugin::remote_execution::ssh:
      :manifest_name: plugin/remote_execution/ssh
      :params_name: plugin/remote_execution/ssh/params
      :dir_name: foreman_proxy
    :foreman_proxy::plugin::salt:
      :manifest_name: plugin/salt
      :params_name: plugin/salt/params
      :dir_name: foreman_proxy
