name    'theforeman-tftp'
version '1.2.0'
source 'git://github.com/theforeman/puppet-tftp'
author 'theforeman'
license 'GPLv3+'
summary 'TFTP server configuration'
description 'Module for configuring a TFTP server'
project_page 'http://github.com/theforeman/foreman-installer'

dependency 'puppetlabs/xinetd'
