def error(message)
  say message
  logger.error message
  kafo.class.exit 101
end

ssl_directory = param('certs', 'ssl_build_dir')
certs_tar = param('foreman_proxy_certs', 'certs_tar') || param('foreman_proxy_content', 'certs_tar')

if certs_tar.value
  certs_tar.value = File.expand_path(certs_tar.value)
end

# On existing installs, check to see if ssl_directory exists and if so skip the certs_tar value check
if File.file?('./config/last_scenario.yaml')
  if param('certs', 'deploy').value && !(File.file?(certs_tar.value) && Dir.exist?(ssl_directory.value))
    error "The certs tar file generated by the server is not present at #{certs_tar.value}, exiting."
    # On new installs, check to see if the certs_tar file is present
  elsif param('certs', 'deploy').value && !File.file?(certs_tar.value)
    error "The certs tar file generated by the server is not present at #{certs_tar.value}, exiting."
  end
end
