def error(message)
  say message
  logger.error message
  kafo.class.exit 101
end

if param('capsule', 'certs_tar') && (certs_tar = param('capsule', 'certs_tar').value)
  unless File.file?(certs_tar)
    error "The certs tar file generated by the server is not present at #{certs_tar}, exiting."
  end
end
