name    'theforeman-concat_native'
version '1.3.0'
source 'git://github.com/theforeman/puppet-concat'
author 'Onyx Point, Inc.'
license 'Apache 2.0'
summary 'Puppet Concat Module'
description 'Module that provides a native type for performing multi-part file concatenation.'
project_page 'http://github.com/theforeman/foreman-installer'
